spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zenith
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
  servlet:
    session:
      timeout: 120m
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

server:
  servlet:
    session:
      cookie:
        name: ZENITH_TOKEN
        http-only: true
        secure: false
        same-site: strict
        path: /
  web:
    resources:
      static-locations: file:uploads/

session:
  max-concurrent: 5
  timeout-minutes: 120
  kicked-record-expire-minutes: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
