spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zenith
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
  servlet:
    session:
      timeout: 30m

server:
  servlet:
    session:
      cookie:
        name: ZENITH_TOKEN
        http-only: true
        secure: false
        same-site: lax
        max-age: 1800
        path: /
  web:
    resources:
      static-locations: file:uploads/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
