spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zenith
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: file:uploads/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
